"""
Django settings for waterworks project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
import dj_database_url
from decouple import config, Csv

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: Keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-' + get_random_secret_key())

# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Render environment detection
RENDER_ENVIRONMENT = config('RENDER', default='')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,192.168.100.9', cast=Csv())

# Add Render domain for production deployment
if RENDER_ENVIRONMENT or '.onrender.com' not in str(ALLOWED_HOSTS):
    ALLOWED_HOSTS.append('.onrender.com')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'corsheaders',  # For Android app API
    'consumers',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'corsheaders.middleware.CorsMiddleware',  # CORS for Android app
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'waterworks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'consumers' / 'templates',  # ✅ App-level base.html
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'consumers.context_processors.notifications',  # Custom notification context
            ],
        },
    },
]

WSGI_APPLICATION = 'waterworks.wsgi.application'

# Database
# DATABASE_URL must be provided via environment variable
# For local development, use SQLite by not setting DATABASE_URL
# For production (Render/Neon), set DATABASE_URL in environment
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Use PostgreSQL database (Neon/Render) from environment variable
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Local development database (fallback to SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Only include STATICFILES_DIRS if the directory exists
static_dir = os.path.join(BASE_DIR, 'static')
if os.path.exists(static_dir):
    STATICFILES_DIRS = [static_dir]

# WhiteNoise configuration for serving static files
# Use CompressedStaticFilesStorage (NOT Manifest version) for Render compatibility
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL
LOGIN_URL = '/login/'

# Session settings - Auto-logout after 3 minutes of inactivity
# Session persists across page refreshes and browser tabs
# Session lasts 8 hours (a full work day) and resets on every request
SESSION_COOKIE_AGE = 28800  # 8 hours in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session ends when browser is closed
SESSION_SAVE_EVERY_REQUEST = True  # Reset session expiry on every request (activity)

# Message storage - Use session only so messages are cleared on logout
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# CORS Settings for Android App
# Initialize as empty list, then add from config if provided
CORS_ALLOWED_ORIGINS = []
_cors_config = config('CORS_ALLOWED_ORIGINS', default='')
if _cors_config:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in _cors_config.split(',') if origin.strip()])

# Allow credentials (for session-based auth from mobile app)
CORS_ALLOW_CREDENTIALS = True

# Allow these methods for API
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow these headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Settings for API endpoints
# Initialize as empty list, then add from config if provided
CSRF_TRUSTED_ORIGINS = []
_csrf_config = config('CSRF_TRUSTED_ORIGINS', default='')
if _csrf_config:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in _csrf_config.split(',') if origin.strip()])

# Add Render production domain to trusted origins
CSRF_TRUSTED_ORIGINS.extend([
    'https://*.onrender.com',
])

# CORS for mobile app - restrict origins in production
# Mobile apps don't send Origin header the same way browsers do, 
# but allowing all is a security risk in production.
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=DEBUG, cast=bool)
# CSRF and Session Cookie Configuration
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ============================================================================
# EMAIL CONFIGURATION - Gmail SMTP for password reset tokens
# ============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # Important: Use TLS, not SSL

# Gmail credentials - strip whitespace to avoid auth errors
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='').strip()
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='').strip()

# IMPORTANT: Gmail requires from_email to match the authenticated user
# Use EMAIL_HOST_USER as the from address for Gmail SMTP
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@balilihan-waterworks.com'
SERVER_EMAIL = EMAIL_HOST_USER

# Email timeout settings (increased for reliability)
EMAIL_TIMEOUT = 30  # seconds

# Debug logging for email configuration (only logs non-sensitive info)
import logging
_email_logger = logging.getLogger('email_config')
if EMAIL_HOST_USER:
    _email_logger.info(f"Email configured with user: {EMAIL_HOST_USER}")
else:
    _email_logger.warning("EMAIL_HOST_USER is not configured!")
if not EMAIL_HOST_PASSWORD:
    _email_logger.warning("EMAIL_HOST_PASSWORD is not configured!")

# ============================================================================
# CLOUDINARY CONFIGURATION - For proof image uploads (API direct upload)
# ============================================================================
# Environment variables on Render:
# - CLOUDINARY_CLOUD_NAME = dpuynl0ir
# - CLOUDINARY_API_KEY = 164721132444788
# - CLOUDINARY_API_SECRET = (configured)
CLOUDINARY_AVAILABLE = False
try:
    import cloudinary
    import cloudinary.uploader
    CLOUDINARY_AVAILABLE = True

    _cloud_name = config('CLOUDINARY_CLOUD_NAME', default='')
    _api_key = config('CLOUDINARY_API_KEY', default='')
    _api_secret = config('CLOUDINARY_API_SECRET', default='')

    if _cloud_name and _api_key and _api_secret:
        cloudinary.config(
            cloud_name=_cloud_name,
            api_key=_api_key,
            api_secret=_api_secret,
            secure=True
        )
        _email_logger.info(f"Cloudinary configured with cloud: {_cloud_name}")
    else:
        _email_logger.warning("Cloudinary credentials not configured! Proof image uploads will fail.")
except ImportError:
    _email_logger.warning("Cloudinary package not installed. Proof image uploads will not work.")

# Add Render domain to trusted origins dynamically
if RENDER_ENVIRONMENT:
    render_external_url = config('RENDER_EXTERNAL_URL', default='')
    if render_external_url:
        CSRF_TRUSTED_ORIGINS.append(render_external_url)

# Security settings (for production)
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Render handles SSL termination at the load balancer
    # Note: CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE are set above based on DEBUG

    # Logging configuration for production - Reduced to prevent rate limiting
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
                'level': 'WARNING',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
            'django.server': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }